In [20]:
#5
import numpy as np
import scipy
with open("Advertising.csv") as f:
    data = f.read().split("\n")
    
good_data = []
for d in data[1: -1]:
    d = d.split(",")
    good_data.append({"sales": float(d[-1]), "TV": float(d[1])})

n = 20000
np.random.seed(0)
sample_size = len(good_data)
r = range(sample_size)
sample = []

def fun(x):
    global sample
    c, b = x
    return (np.array([s["sales"] - c - b * s["TV"] for s in sample]) ** 2).sum()

samples = []

for i in range(n):
    sample = np.random.choice(good_data, sample_size)
    res = scipy.optimize.minimize(fun, x0 = (0, 0))
    samples.append(res.x)

np.corrcoef(np.array(samples).T)

array([[ 1.        , -0.83770217],
       [-0.83770217,  1.        ]])

In [21]:
#2
import numpy as np
import scipy

with open('casino.txt', 'r') as file:
    data = []
    for row in file.readlines():
        data.append(list(map(int, row.strip().split())))
def func_sample(sample):   
    wins, losses, go_w, go_l = 0, 0, 0, 0
    for game in sample:
        wins += sum(game)
        losses += len(game) - sum(game)
        if game[-1] == 0:
            go_l += 1
        else:
            go_w += 1

    def func(x):
        p_w, p_go_w, p_go_l = x
        res = (np.log(p_w) * wins 
           + np.log(1 - p_w) * losses 
           + np.log(p_go_l) * go_l
           + np.log(1 - p_go_l) * (losses - go_l)
           + np.log(p_go_w) * go_w
           + np.log(1 - p_go_w) * (wins - go_w))
        return -res
    return func

bounds = [(1e-5, 1-1e-5), (1e-5, 1-1e-5), (1e-5, 1-1e-5)]

res = scipy.optimize.minimize(func_sample(data), (0.5, 0.5, 0.5), bounds=bounds)
res.x

array([0.48417558, 0.34059634, 0.75672765])

In [22]:
#3
n = 20000
np.random.seed(0)
sample_size = len(data)
choice = range(sample_size)
diffs = []
bounds = [(1e-5, 1-1e-5), (1e-5, 1-1e-5), (1e-5, 1-1e-5)]
for i in range(n):
    chooses = np.random.choice(choice, size=sample_size)
    sample = []
    for c in chooses:
        sample.append(data[c])
    res = scipy.optimize.minimize(func_sample(sample), (0.5, 0.5, 0.5), bounds=bounds)
    diffs.append(res.x[2] - res.x[1])

quantile = 0.95
np.quantile(diffs, q=[(1 - quantile)/2, quantile + (1 - quantile)/2])

array([0.37639087, 0.45542335])

In [23]:
#4
import scipy
import math

def f(x):
    return (2 / math.pi) * (24 * x + 1) * (1 - x + x / 5) ** 2 - 1

scipy.optimize.root_scalar(f, bracket=[0, 3], method='brentq')

      converged: True
           flag: 'converged'
 function_calls: 8
     iterations: 7
           root: 0.02666780668672309

In [24]:
#1
import scipy
import math
import numpy as np
import scipy.stats as sps

data = np.array([(576, 3.39), (635, 3.30), (558, 2.81), (578, 3.03), (666, 3.44),
                 (580, 3.07), (555, 3.0), (661, 3.43), (651, 3.36), (605, 3.13),
                 (653, 3.12), (575, 2.74), (545, 2.76), (572, 2.88), (594, 2.96)])

coeff = np.corrcoef(data.T)[0, 1]
alpha = 0.95
right = sps.norm().ppf((1 + alpha) / 2)
left = sps.norm().ppf((1 - alpha) / 2)

def center(n, z, c):
    def f(x):
        return z * (1 - x ** 2) - math.sqrt(n) * (c - x)
    return f

r = scipy.optimize.root_scalar(center(len(data), left, coeff), bracket=[0, 1], method='brentq').root
l = scipy.optimize.root_scalar(center(len(data), right, coeff), bracket=[0, 1], method='brentq').root
print(f"{l} {r}")

0.3231645687328099 0.8855673805132537
